// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbWlOdYjNhPt2TLT7jUt7OtF9K1BLRwjk',
    appId: '1:299988428181:web:883915235e62961f33829c',
    messagingSenderId: '299988428181',
    projectId: 'donutappauth',
    authDomain: 'donutappauth.firebaseapp.com',
    storageBucket: 'donutappauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlnrEAtyepaPbCe7ITOYAkFLKIqhyCAAQ',
    appId: '1:299988428181:android:923d1164156782f733829c',
    messagingSenderId: '299988428181',
    projectId: 'donutappauth',
    storageBucket: 'donutappauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg3gpMdvCDs6Q32woCISq5R5ga6Qrlxj4',
    appId: '1:299988428181:ios:36e8d9d7215f847b33829c',
    messagingSenderId: '299988428181',
    projectId: 'donutappauth',
    storageBucket: 'donutappauth.appspot.com',
    iosBundleId: 'com.example.donutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg3gpMdvCDs6Q32woCISq5R5ga6Qrlxj4',
    appId: '1:299988428181:ios:36e8d9d7215f847b33829c',
    messagingSenderId: '299988428181',
    projectId: 'donutappauth',
    storageBucket: 'donutappauth.appspot.com',
    iosBundleId: 'com.example.donutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbWlOdYjNhPt2TLT7jUt7OtF9K1BLRwjk',
    appId: '1:299988428181:web:b30bdf73bab666c433829c',
    messagingSenderId: '299988428181',
    projectId: 'donutappauth',
    authDomain: 'donutappauth.firebaseapp.com',
    storageBucket: 'donutappauth.appspot.com',
  );
}
